### ISSUE TITLE
Implement shared memory provisioning for CloudLab

### ISSUE THREAD

**Issue by breezykermo** [breezykermo/oak#11]
From what Deepti told us this morning, it is possible to make a reservation for ~50 nodes on CloudLab, provided the machines are small (64gb of RAM).

Her suggestion on how to provision such a cluster was to upload all of our fvecs into the shared memory API that CloudLab provides, so that the files are accessible to all nodes, and then (as part of a node provisioning phase pre-benchmarking) to load that data into per-node SSD.

I suggest that we do this as part of the implementation of the `dataset` trait in Rust, as we already have the other provisioning step of conditionally loading fvecs into RAM via `mmap.lock()`.

**Comment by csirianni** [comment]
Not necessary for MVP but potentially useful for distributed opportunistic index creation.
