### ISSUE TITLE
Use ACORN as default index in OAK

### ISSUE THREAD

**Issue by csirianni** [breezykermo/oak#35]
1. Update our fork of [ACORN](https://github.com/csirianni/ACORN) to include ACORN functionality in c_api. See [ACORN/#1](https://github.com/csirianni/ACORN/issues/1).
2. Update [acorn-rs](https://github.com/csirianni/acorn-rs) to expose this functionality.
3. Construct an ACORN index in the `index_factory` in OAK.

**Comment by breezykermo** [comment]
Update to the specification after some initial research. Instead of using bindgen, which requires us implementing a lot in the `c_api` folder, we can just define an interface between OAK and ACORN using [cxx](https://github.com/dtolnay/cxx).
