### ISSUE TITLE
Create the presentation

### ISSUE THREAD

**Issue by breezykermo** [breezykermo/oak#47]
For next Tuesday. I'll be there but remote, so @csirianni and @MithiJ you'll have to lead.

We should explain the problem space of vector dbs, ACORN, etc. I think we have a lot of conceptual ground to cover, and then we can speak to our solution with OAK even though it's not complete, i.e. the fact that there will be _some_ query loads in which the additional index construction tradeoff will make sense.

Let's also be sure to talk through our false start with distributed vector DBs

**Comment by MithiJ** [comment]
Linking the slides [here](https://docs.google.com/presentation/d/1FntGuILRY0R-rekx4R-m5KOk447Ld9t9_XEBwFV-7lg/edit?usp=sharing)

**Comment by breezykermo** [comment]
Deepti's guide: https://edstem.org/us/courses/66130/discussion/5812039

**Comment by csirianni** [comment]
Done!
