### ISSUE TITLE
Confirm that `get_data()` works as expected; and that `lock()` on `Mmap` loads files into memory

### ISSUE THREAD

**Issue by breezykermo** [breezykermo/oak#5]
It's sufficient for the time being to simply prove in a test that calling `get_data()` without first calling `lock()` takes longer than calling it with, I would suggest.

@csirianni I'm assigning you if that's okay, as I'd like to get your review and confirmation that the approach works as we expect it to.

**Comment by csirianni** [comment]
Let's also check that `get_data()` returns non-zero values. Or, assert the values for some file are equal to the result of `get_data()` when calling and not calling `lock()`.

**Comment by csirianni** [comment]
Resolved via #6.
