### ISSUE TITLE
Implement `Searchable` trait for `FvecsDataset`

### ISSUE THREAD

**Issue by breezykermo** [breezykermo/oak#6]
This will involve calling [faiss](https://github.com/facebookresearch/faiss) via FFI bindings. We should confirm that it works on a single node (`SsdStandalone`) with Deep1M as the dataset, using Deep1k as a query set.

**Comment by csirianni** [comment]
Update: Implement this over ACORN rather than FAISS.

**Comment by csirianni** [comment]
We initially planned to implement `Searchable` over a `Deep1X` dataset, but we have since decided to use an arbitrary `FvecsDataset` instead.
